name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - feat/deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/my-coin:latest -f frontend/dockerfile frontend

    - name: Authenticate Docker with Google Cloud
      run: echo "${{ secrets.GCLOUD_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Push Docker image to Google Container Registry
      run: docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/my-coin:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-coin \
          --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/my-coin:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated